#!/usr/bin/env ruby
# UpdateGitRevisionNumbers.rb
# buildtools
#
# Copyright 2007-2009 Wincent Colaiuta. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

require_relative './git'
require 'pathname'

target  = Pathname.new 'com.wincent.buildtools.gitrev.h'
rev     = Git::get_rev_number
date    = Time.new.to_s
output  = <<-HEADER

/*
  Autogenerated by UpdateGitRevisionNumbers.rb.
  This file should be ignored by an approriate entry in the .gitignore file.
 */

#define WO_BUILDNUMBER #{rev}
#define WO_BUILDDATE "#{date}"

HEADER

target.open('a+') do |file|
  # check existing contents of file, if any
  file.rewind
  while not file.eof?
    if file.readline =~ /^#define\s+WO_BUILDNUMBER\s+([a-f0-9]{7}\+?)/ and $~[1] == rev
      already_up_to_date = true
      break
    end
  end

  # will only actually modify the file if the revision number has changed
  # (avoids gratuitous rebuilds in Xcode)
  unless already_up_to_date
    file.rewind
    file.truncate 0
    file.print output
  end
end
