#!/usr/bin/env ruby
# UpdateSubversionRevisionNumbers.rb
# buildtools
#
# Created by Wincent Colaiuta on 25 March 2007.
# Copyright 2007 Wincent Colaiuta.
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# in the accompanying file, "LICENSE.txt", for more details.
#

require File.join(File.dirname(__FILE__), 'svk').to_s
require 'pathname'

# use the svn:ignore property to keep this temporary file out of the way
target    = Pathname.new 'com.wincent.buildtools.svnrev.h'
builddate = Time.new
rev       = SVK::get_rev_number
output    = <<-HEADER

/* Autogenerated by UpdateSubversionRevisionNumbers.rb on #{builddate} */

#define WO_BUILDNUMBER     #{rev}
#define WO_BUILDDATE       "#{builddate}"

HEADER

target.open('a+') do |file|
  
  # check existing contents of file, if any
  file.rewind
  while not file.eof?
    if file.readline =~ /^#define\s+WO_BUILDNUMBER\s+(\d+\+?)/ and $~[1] == rev
      already_up_to_date = true
      break
    end
  end
  
  # will only actually modify the file if the revision number has changed (avoids gratuitous rebuilds in Xcode)
  unless already_up_to_date
    file.rewind
    file.truncate 0
    file.print output
  end
  
end
